spring.application.name=ServiceDiscovery

#server.address=127.0.0.1

#service-discovery.dead-services-ttl=90s
#service-discovery.scan-interval=60s

service-discovery.dead-services.ttl=45s
service-discovery.dead-services.scan-interval=30s

service-discovery.old-updates.ttl=2m
service-discovery.old-updates.scan-interval=1m

