spring.application.name=MicroserviceDemo

server.port=8082

service.name=order-service

service-discovery.url=http://localhost:8080/service-discovery
service-discovery.register.path=/register
service-discovery.listen.path=/listen
service-discovery.unregister.path=/unregister

load-balancing-algorithm=ROUND_ROBIN

#heart-beating-interval=30s
heart-beating-interval=15s

service.auto-register.enabled=true

# Enable graceful shutdown
#server.shutdown=graceful